### ISSUE TITLE
Who has the copyright of this repo and what is the License?

### ISSUE THREAD

**Issue by thanpolas** [i18next/i18next-gitbook#88]
what the title says

**Comment by jamuhl** [comment]
you talking about the documentation repo? or i18next?

https://github.com/i18next/i18next/blob/master/LICENSE

**Comment by jamuhl** [comment]
MIT

**Comment by thanpolas** [comment]
hmmm I probably got lost as I landed from googling... Thanks for the information.

**Comment by gilbsgilbs** [comment]
Hi,

I'd like to know what is the license of the documentation and the logo. I might use the logo in a derivative work (for [babel-plugin-i18next-extract](https://github.com/i18next/i18next.com/tree/6cff15e5dc24b0dde8f9835adce9ac2449693b00)). It would be nice to make it clear whether I can or cannot do this. Thanks :)

**Comment by jamuhl** [comment]
@gilbsgilbs sure you can use it if related...

**Comment by gilbsgilbs** [comment]
> @gilbsgilbs sure you can use it if related...

Nice, thanks.

I'm not an expert at all, yet I don't think disallowing usage of the logo in non i18next-related projects is MIT-compatible. This causes a tiny issue for me because I don't know under which license I am allowed to release my derivative work (definitely not MIT which is the license of my repo).

I hate this kind of useless and time-consuming discussions and I feel very sorry about this :disappointed: .

**Comment by jamuhl** [comment]
The logo itself (and docs) has no explicit licence (I'm not a lawyer - but guess this makes it all rights reserved) -> the i18next code repo is MIT licenced...

**Comment by jamuhl** [comment]
But as said...do with it what is useful...as long you don't make a commercial project with it ;)

**Comment by gilbsgilbs** [comment]
Thanks for the clarification @jamuhl .
